export const POPULAR_LOCATIONS = [
    { value: "patna", label: "Patna, Bihar" },
    { value: "gaya", label: "Gaya, Bihar" },
    { value: "bhagalpur", label: "Bhagalpur, Bihar" },
    { value: "muzaffarpur", label: "Muzaffarpur, Bihar" },
    { value: "purnia", label: "Purnia, Bihar" },
    { value: "darbhanga", label: "Darbhanga, Bihar" },
    { value: "biharsharif", label: "Bihar Sharif, Bihar" },
    { value: "arrah", label: "Arrah, Bihar" },
    { value: "begusarai", label: "Begusarai, Bihar" },
    { value: "katihar", label: "Katihar, Bihar" },
    { value: "munger", label: "Munger, Bihar" },
    { value: "chhapra", label: "Chhapra, Bihar" },
    { value: "danapur", label: "Danapur, Bihar" },
    { value: "bettiah", label: "Bettiah, Bihar" },
    { value: "saharsa", label: "Saharsa, Bihar" },
    { value: "sasaram", label: "Sasaram, Bihar" },
    { value: "hajipur", label: "Hajipur, Bihar" },
    { value: "dehri", label: "Dehri, Bihar" },
    { value: "siwan", label: "Siwan, Bihar" },
    { value: "motihari", label: "Motihari, Bihar" },
    { value: "nawada", label: "Nawada, Bihar" },
    { value: "buxar", label: "Buxar, Bihar" },
    { value: "kishanganj", label: "Kishanganj, Bihar" },
    { value: "sitamarhi", label: "Sitamarhi, Bihar" },
    { value: "mumbai", label: "Mumbai, Maharashtra" },
    { value: "delhi", label: "New Delhi, Delhi" },
    { value: "goa", label: "Goa, India" },
    { value: "bangalore", label: "Bangalore, Karnataka" },
    { value: "jaipur", label: "Jaipur, Rajasthan" },
    { value: "udaipur", label: "Rajasthan" },
    { value: "chennai", label: "Chennai, Tamil Nadu" },
    { value: "hyderabad", label: "Hyderabad, Telangana" },
    { value: "kolkata", label: "Kolkata, West Bengal" },
];
